version: "3"
services:
  api-database:
    image: mongo
    container_name: "mongo-server" 
    volumes:
       - /mongo-data:/data/db
     
  api:
    image: api-docker-app
    ports:
     - "5000:8080"
    deploy:
      replicas: 2	
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
     
