version: '3.0'
services:
   web:
    image: pbadhe34/my-apps:user-app
    ports:
       - "5000:8090"
    networks:
       - webnet     
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  mysql:    
     image: mysql:5.6
     volumes:
       - "/mysql/data:/var/lib/mysql"
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: userservice
       MYSQL_USER: app-user
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password    


secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

