version: '3.1'
services:
  web:
    image: pbadhe34/my-apps:user-app
    ports:
       - "5000:8090"
    networks:
       - webnet     
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:5.6    
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mypass
      MYSQL_DATABASE: userservice
      MYSQL_USER: app-user
      MYSQL_PASSWORD: /run/secrets/mypass
    volumes:
       - "/mysql/data:/var/lib/mysql"
    secrets:
       - mypass   
    networks:
       - webnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy: 
       condition: on-failure
secrets:
  mypass:
    external: true
networks:
  webnet:
