version: '3'
services:
  web-app:
    image: pbadhe34/my-apps:app1
    ports:
     - "5000:8090"
    deploy:
      replicas: 2	
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure  
    networks:
       - webnet
    
  redis-host:
    image: "redis"
    volumes:
     - /redis-volume:/data
    deploy:
       replicas: 1
       placement:
         constraints: [node.role == manager]
       update_config:
         parallelism: 1
         delay: 10s
       restart_policy:
         condition: on-failure
    networks:
       - webnet
networks:
   webnet:
